import streamlit as st

st.set_page_config(page_title="Terms and Conditions - LIG Visualization Tool", layout="wide")

st.title("Terms and Conditions")
st.markdown("""
**Effective Date**: June 10, 2025

Welcome to the LIG Visualization Tool ("Service"), accessible at [https://oceanicmonk-lig-visualization-tool-app-bxe29c.streamlit.app/](https://oceanicmonk-lig-visualization-tool-app-bxe29c.streamlit.app/). By accessing or using the Service, you agree to be bound by these Terms and Conditions ("Terms"). If you do not agree, please do not use the Service.

### 1. Acceptance of Terms
These Terms govern your use of the Service, including free trials (50/month) and Premium subscriptions. We may update these Terms periodically, and continued use constitutes acceptance of changes.

### 2. Eligibility
You must be at least 13 years old to use the Service. By using the Service, you represent that you meet this requirement.

### 3. Account and Subscription
- **Free Tier**: Provides 50 trials/month for 2D/3D visualizations and animations, tracked via `usage.log`.
- **Premium Tier**: Offers unlimited trials and downloadable reports for $5/month (≈ ₹428/month), processed via Razorpay.
- **Account Security**: You are responsible for maintaining the confidentiality of your email and payment details.
- **Cancellation**: You may cancel your Premium subscription via Razorpay’s dashboard or by contacting us. No partial refunds are issued.

### 4. Use of the Service
- **Permitted Use**: You may use the Service for personal or research purposes to generate logarithmic intrinsic geometry visualizations.
- **Prohibited Use**: You may not reverse-engineer, distribute, or use the Service for illegal activities, or exceed trial limits without a subscription.
- **Trial Limits**: Free users are limited to 50 trials/month, reset monthly. Trials are tracked by email or anonymous ID.

### 5. Intellectual Property
All content, code, and visualizations generated by the Service are owned by Serene Glade or licensed to us. You may not reproduce or distribute content without permission, except for personal use of Premium reports.

### 6. Payment and Refunds
- **Payment**: Premium subscriptions are billed monthly via Razorpay.
- **Refunds**: See our [Refund Policy](https://oceanicmonk-lig-visualization-tool-app-bxe29c.streamlit.app/refund_policy) for details.
- **Taxes**: Prices exclude applicable taxes, which are your responsibility.

### 7. Termination
We may suspend or terminate your access for violating these Terms, non-payment, or at our discretion. Upon termination, your data may be deleted per our Privacy Policy.

### 8. Disclaimer of Warranties
The Service is provided "as is" without warranties. We do not guarantee accuracy, availability, or error-free operation.

### 9. Limitation of Liability
To the extent permitted by law, we are not liable for indirect, incidental, or consequential damages arising from your use of the Service. Our total liability is limited to the amount paid for the Premium subscription.

### 10. Governing Law
These Terms are governed by the laws of India, with disputes resolved in the courts of Kerala.

### 11. Contact Us
For questions or concerns, contact:  
- **Name**: Serene Glade  
- **Email**: [oceanicmonk@gmail.com](mailto:oceanicmonk@gmail.com)  
- **Phone**: +91 9745059169  
- **Address**: Ambalaparambil, Kerala-676509, India  
- **Website**: [https://oceanicmonk-lig-visualization-tool-app-bxe29c.streamlit.app/](https://oceanicmonk-lig-visualization-tool-app-bxe29c.streamlit.app/)

By using the Service, you acknowledge that you have read and agree to these Terms.
""")